import re

with open('docs/architecture-build-steps.html', 'r') as f:
    text = f.read()

diagrams = {
    "Create the VPC": """direction: down
vars: { d2-config: { theme-id: 200 } }
aws: "☁️ AWS Cloud" {
  style.fill: "#1e1f29"; style.stroke: "#ff9900"; style.stroke-width: 2
  vpc: "🖧 Customer VPC\\\\n10.0.0.0/16" {
    shape: package
    style.fill: "#282a36"; style.stroke: "#50fa7b"; style.stroke-width: 2
    dns: "DNS Resolver" { shape: cylinder; style.fill: "#bd93f9"; style.font-color: "#f8f8f2" }
  }
}""",
    
    "Enable VPC Flow Logs": """direction: right
vars: { d2-config: { theme-id: 200 } }
vpc: "�� Customer VPC" { 
  style.fill: "#1e1f29"; style.stroke: "#50fa7b"; style.stroke-width: 2
  traffic: "🔄 All Network Traffic\\\\n(ACCEPT & REJECT)" { shape: hexagon; style.fill: "#ff79c6"; style.font-color: "#282a36" }
}
flow: "📉 VPC Flow Logs" { shape: cylinder; style.fill: "#bd93f9"; style.font-color: "#f8f8f2" }
cw: "☁️ CloudWatch\\\\n(30 Days Retention)" { shape: cloud; style.fill: "#6272a4"; style.font-color: "#f8f8f2" }

vpc.traffic -> flow: "ENI Data" { style.stroke: "#f8f8f2"; style.stroke-dash: 5 }
flow -> cw: "Log Streams" { style.stroke: "#bd93f9"; style.stroke-dash: 5 }""",

    "Create KMS Key": """direction: right
vars: { d2-config: { theme-id: 200 } }
kms: "🔑 KMS Master Key\\\\n(Envelope Encryption)" { shape: hexagon; style.fill: "#ff5555"; style.font-color: "#f8f8f2" }
dek: "🎫 Data Encryption Key\\\\n(Generated by KMS)" { shape: document; style.fill: "#f1fa8c"; style.font-color: "#282a36" }
k8s: "Kubernetes Secrets" {
  style.fill: "#1e1f29"; style.stroke: "#bd93f9"
  etcd: "🗄️ etcd Database" { shape: cylinder; style.fill: "#44475a"; style.font-color: "#f8f8f2" }
}

kms -> dek: "1. Creates & Encrypts DEK" { style.stroke: "#f8f8f2"; style.stroke-dash: 5 }
dek -> k8s.etcd: "2. Encrypts Secrets Data" { style.stroke: "#f1fa8c"; style.stroke-dash: 5 }""",

    "Create Security Groups + Rules": """direction: right
vars: { d2-config: { theme-id: 200 } }
csg: "🛡️ Cluster SG\\\\n(EKS Control Plane)" { shape: hexagon; style.fill: "#ffb86c"; style.font-color: "#282a36" }
nsg: "🛡️ Node SG\\\\n(EC2 Worker Nodes)" { shape: hexagon; style.fill: "#8be9fd"; style.font-color: "#282a36" }

# Rules
nsg -> csg: "Ingress 443 (kubelet to API)" { style.stroke: "#50fa7b"; style.stroke-dash: 5 }
csg -> nsg: "Ingress 1025-65535 (API to kubelet/exec)" { style.stroke: "#bd93f9"; style.stroke-dash: 5 }
nsg -> nsg: "Ingress All Ports (Pod-to-Pod)" { style.stroke: "#f1fa8c"; style.stroke-dash: 5 }""",

    "Register OIDC Provider (IRSA)": """direction: down
vars: { d2-config: { theme-id: 200 } }
oidc: "🛡️ OIDC Identity Provider\\\\n(IAM Integration)" { shape: hexagon; style.fill: "#bd93f9"; style.font-color: "#f8f8f2" }

pods: "Kubernetes Namespace" {
  style.fill: "#1e1f29"; style.stroke: "#6272a4"; style.stroke-width: 2
  sa1: "🎫 ServiceAccount (S3 Read)" { shape: document; style.fill: "#44475a"; style.font-color: "#f8f8f2" }
  sa2: "🎫 ServiceAccount (Dynamo Write)" { shape: document; style.fill: "#44475a"; style.font-color: "#f8f8f2" }
  
  pod1: "📦 App Pod 1" { shape: package; style.fill: "#8be9fd"; style.font-color: "#282a36" }
  pod2: "📦 App Pod 2" { shape: package; style.fill: "#8be9fd"; style.font-color: "#282a36" }
}

oidc -> pods.sa1: "STS AssumeRoleWithWebIdentity" { style.stroke: "#f8f8f2"; style.stroke-dash: 5 }
oidc -> pods.sa2 { style.stroke: "#f8f8f2"; style.stroke-dash: 5 }
pods.sa1 -> pods.pod1: "Mounted Token" { style.stroke: "#bd93f9"; style.stroke-dash: 5 }
pods.sa2 -> pods.pod2: "Mounted Token" { style.stroke: "#bd93f9"; style.stroke-dash: 5 }""",

    "Install EKS Add-ons": """direction: down
vars: { d2-config: { theme-id: 200 } }
worker: "🖥️ EC2 Worker Node" {
  style.fill: "#1e1f29"; style.stroke: "#6272a4"; style.stroke-width: 2
  
  cni: "🌐 VPC CNI (DaemonSet)\\\\nManages ENIs & VPC IPs" { shape: hexagon; style.fill: "#ffb86c"; style.font-color: "#282a36" }
  kp: "🔀 kube-proxy (DaemonSet)\\\\nManages iptables routing" { shape: hexagon; style.fill: "#8be9fd"; style.font-color: "#282a36" }
  dns: "🔍 CoreDNS (Deployment)\\\\nCluster DNS Resolution" { shape: hexagon; style.fill: "#50fa7b"; style.font-color: "#282a36" }
}
vpc: "🖧 Customer VPC" { shape: package; style.fill: "#44475a"; style.font-color: "#f8f8f2" } 
worker.cni -> vpc: "Assigns real IPs to Pods" { style.stroke: "#ffb86c"; style.stroke-dash: 5 }""",

    "Create Launch Templates": """direction: right
vars: { d2-config: { theme-id: 200 } }
admin: "💻 Terraform" { shape: person; style.fill: "#6272a4" }

lt: "📜 EC2 Launch Template" {
  style.fill: "#1e1f29"; style.stroke: "#bd93f9"; style.stroke-width: 2
  imds: "🔐 IMDSv2 Enforced\\\\n(Blocks SSRF)" { shape: rectangle; style.fill: "#ff5555"; style.font-color: "#f8f8f2" }
  ebs: "💾 gp3 Volumes\\\\n(Encrypted, 3000 IOPS)" { shape: cylinder; style.fill: "#ffb86c"; style.font-color: "#282a36" }
  net: "🌐 Network Interfaces\\\\n(No Public IPs)" { shape: rectangle; style.fill: "#8be9fd"; style.font-color: "#282a36" }
}

asg: "⚙️ EKS Node Group (ASG)" { shape: hexagon; style.fill: "#50fa7b"; style.font-color: "#282a36" }

admin -> lt: "Defines Baseline" { style.stroke: "#f8f8f2"; style.stroke-dash: 5 }
lt -> asg: "Used to provision instances" { style.stroke: "#bd93f9"; style.stroke-dash: 5 }""",

    "Create Secrets + KMS Key": """direction: down
vars: { d2-config: { theme-id: 200 } }
sm: "🔐 AWS Secrets Manager" {
  style.fill: "#1e1f29"; style.stroke: "#ffb86c"; style.stroke-width: 2
  
  db: "🗄️ Database Credentials" { shape: document; style.fill: "#f1fa8c"; style.font-color: "#282a36" }
  api: "🔌 External API Keys" { shape: document; style.fill: "#f1fa8c"; style.font-color: "#282a36" }
  app: "⚙️ App Configurations" { shape: document; style.fill: "#f1fa8c"; style.font-color: "#282a36" }
}

kms: "🔑 Custom KMS Key\\\\n(Dedicated to Secrets)" { shape: hexagon; style.fill: "#ff5555"; style.font-color: "#f8f8f2" }

kms -> sm.db: "Encrypts at rest" { style.stroke: "#ff79c6"; style.stroke-dash: 5 }
kms -> sm.api: "Encrypts at rest" { style.stroke: "#ff79c6"; style.stroke-dash: 5 }
kms -> sm.app: "Encrypts at rest" { style.stroke: "#ff79c6"; style.stroke-dash: 5 }""",

    "Create Read-Only IAM Policy": """direction: right
vars: { d2-config: { theme-id: 200 } }
pod: "📦 Application Pod\\\\n(via IRSA)" { shape: package; style.fill: "#8be9fd"; style.font-color: "#282a36" }

iam: "🛡️ IAM Policy (Read-Only)" {
  style.fill: "#1e1f29"; style.stroke: "#ff5555"; style.stroke-width: 2
  p1: "ALLOW: secretsmanager:GetSecretValue\\\\n(Only specific ARNs)" { shape: rectangle; style.fill: "#ffb86c"; style.font-color: "#282a36" }
  p2: "ALLOW: kms:Decrypt\\\\n(Only dedicated KMS Key)" { shape: rectangle; style.fill: "#ffb86c"; style.font-color: "#282a36" }
}

sm: "🔐 Secrets Vault" { shape: cylinder; style.fill: "#bd93f9"; style.font-color: "#282a36" }

pod -> iam { style.stroke: "#f8f8f2"; style.stroke-dash: 5 }
iam.p1 -> sm: "Read Secret" { style.stroke: "#50fa7b"; style.stroke-dash: 5 }
iam.p2 -> sm: "Decrypt via KMS" { style.stroke: "#50fa7b"; style.stroke-dash: 5 }""",

    "Enable GuardDuty": """direction: right
vars: { d2-config: { theme-id: 200 } }
sources: "📊 Audit & Network Sources" {
  style.fill: "#1e1f29"; style.stroke: "#6272a4"
  vfl: "VPC Flow Logs" { shape: document; style.fill: "#6272a4"; style.font-color: "#f8f8f2" }
  k8s: "EKS Audit Logs" { shape: document; style.fill: "#6272a4"; style.font-color: "#f8f8f2" }
  dns: "Route 53 DNS Logs" { shape: document; style.fill: "#6272a4"; style.font-color: "#f8f8f2" }
}

gd: "🛡️ AWS GuardDuty" {
  style.fill: "#282a36"; style.stroke: "#bd93f9"; style.stroke-width: 2
  det: "🧠 Machine Learning Detector\\\\n(Updates every 15 min)" { shape: hexagon; style.fill: "#bd93f9"; style.font-color: "#282a36" }
}

alert: "🚨 Security Findings\\\\n(Crypto mining, Exploit attempts)" { shape: callout; style.fill: "#ff5555"; style.font-color: "#f8f8f2" }

sources.vfl -> gd.det: "Analyzes" { style.stroke: "#f8f8f2"; style.stroke-dash: 5 }
sources.k8s -> gd.det: "Analyzes" { style.stroke: "#f8f8f2"; style.stroke-dash: 5 }
sources.dns -> gd.det: "Analyzes" { style.stroke: "#f8f8f2"; style.stroke-dash: 5 }
gd.det -> alert: "Generates Alerts" { style.stroke: "#ff5555"; style.stroke-dash: 5; style.stroke-width: 2 }""",

}

new_text = text
for title, d2_code in diagrams.items():
    pattern = re.compile(r'(title:\s*"' + re.escape(title) + r'".*?d2:\s*`)(.*?)(`,\s*note:)', re.DOTALL)
    
    def replacer(m):
        return m.group(1) + d2_code + m.group(3)
    
    new_text = pattern.sub(replacer, new_text)

with open('docs/architecture-build-steps.html', 'w') as out:
    out.write(new_text)

print("Updated multiline strings!")
